name = "SequentialRaytrace"
uuid = "e6e29653-ad00-4000-b95c-264f03acb66e"
authors = ["Danny Chan"]
version = "0.1.0"

[deps]
ResultTypes = "08a2b407-ddc3-586a-afd6-c784ad1fffe2"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
